[project]
name = "asb-ofw-wrangler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ofxtools",
]

[dependency-groups]
dev = [
    "black",
]
